# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: obs-limit-range
#   namespace: obs
# spec:
#   limits:
#   - type: Container
#     default: # this section defines default limits
#       cpu: 100m
#       memory: 256Mi
#     defaultRequest: # this section defines default requests
#       cpu: 50m
#       memory: 128Mi