apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-api-images
  namespace: api
data:
  OTEL_SERVICE_NAME: api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://my-opentelemetry-collector.obs.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_INSECURE: 'true'
  OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: 'true'
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-catalogo
  namespace: api
data:
  OTEL_SERVICE_NAME: catalogo
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://my-opentelemetry-collector.obs.svc.cluster.local:4318/v1/traces
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://my-opentelemetry-collector.obs.svc.cluster.local:4318/v1/metrics
  OTEL_EXPORTER_OTLP_INSECURE: 'true'
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp